platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: '2.5'

inputs:
  - name: source
  - name: metadata

outputs:
  - name: test

params:
  PR:

run:
  path: bash
  args:
  - -c
  - |
    set -e -x

    cp -r source/. test/
    cd test

    bundle install
    bundle exec rubocop --fail-level autocorrect
    bundle exec rake test
